Ajout readmes
Don-t-ttach-my-documents/don-t-ttach-my-documents pull request #14
Opened 2023-02-28 15:45 UTC by Hugov8

2023-02-28 17:07 UTC, remiCzn requested changes

2023-02-28 17:07 UTC, remiCzn commented on archive-cli/README.md
> +Le cronjob va se contenter de lancer le service archive-cli du [docker-compose](/docker-compose.yml). Ce service va exécuté le script [archive_data](/archive-cli/archive_data.sh), ayant pour but de s
```suggestion
Le cronjob va se contenter de lancer le service archive-cli du [docker-compose](/docker-compose.yml). Ce service va exécuter le script [archive_data](/archive-cli/archive_data.sh), ayant pour but de supprimer tous les fichiers datant de plus de *Delay*. Ce délai peut être changé dans le [docker-compose](/docker-compose.yml).
```

2023-02-28 17:07 UTC, remiCzn commented on filestorageapi/README.md
> +A minio server should be up to execute
Un peu bizarre d'avoir de l'anglais ici et du français ailleurs dans les readme, il faudrait à mon avis avoir soit du français partout, soit de l'anglais partout (plus chaud pour le français)
Tu peux changer ça dans cette PR?

2023-02-28 19:15 UTC, Hugov8 commented
J'en ai profité pour repasser les commentaires des codes en français

2023-03-01 07:03 UTC, remiCzn approved these changes

2023-03-02 08:42 UTC, merged