Dockerize avec parsing et file storage
Don-t-ttach-my-documents/don-t-ttach-my-documents pull request #3
Opened 2022-12-06 09:38 UTC by remiCzn

2022-12-07 19:40 UTC, Hugov8 commented
J'ai une erreur quand j'essaie de récupérer la pièce jointe via le lien envoyé
![image](https://user-images.githubusercontent.com/91616718/206278607-3ef5b01f-6f27-4003-9f1b-ecfbde46f960.png)
![image](https://user-images.githubusercontent.com/91616718/206278679-a41b387f-3e8d-4317-bb72-26a2ba000978.png)
La pièce jointe s'upload bien par contre quand on regarde avec l'interface de minio

2022-12-07 19:49 UTC, Hugov8 requested changes
et voir le problème posté en commentaire de la PR

2022-12-07 19:49 UTC, Hugov8 commented on filestorageapi/index.py
> +BUCKET_NAME = "don-t-ttach-my-docs"
Séparer en deux fichiers python l'API et la gestion de minio ? Ce sera plus facile pour s'y retrouver si notre code grandit

2022-12-08 09:22 UTC, remiCzn commented on filestorageapi/index.py
> +BUCKET_NAME = "don-t-ttach-my-docs"
C'est bon c'est fait, dis moi si ça te va

2022-12-08 10:17 UTC, Hugov8 requested changes
Supprimer les prints qui ont servi au debug (ma faute dsl)

2022-12-08 10:20 UTC, Hugov8 requested changes
Supprimer les print qui ont servi au debug, on les remettra en local si on en a besoin (ma faute dsl)

2022-12-08 10:23 UTC, Hugov8 requested changes

2022-12-08 10:23 UTC, Hugov8 commented on parsing/index.py
> +    # print(res)
supprimer print

2022-12-08 10:23 UTC, Hugov8 commented on parsing/parsing.py
> +        # print(link.json())
idem

2022-12-08 10:23 UTC, Hugov8 commented on parsing/parsing.py
> +        print("Can't connect to " + URL_TO_FILE_SERVER)
Vu qu'on a dockerizé on peut ici juste tracé l'erreur avec un print et retourné la pièce jointe tel quel sans lien en cas d'erreur, je m'en servais surtout pour tester sans tout lancer

2022-12-08 10:23 UTC, Hugov8 commented on parsing/parsing.py
> +    # print(deformat_headers(parse_mime_files(msg)))
idem

2022-12-08 10:24 UTC, Hugov8 commented on filestorageapi/index.py
> +BUCKET_NAME = "don-t-ttach-my-docs"
parfait

2022-12-08 16:47 UTC, Hugov8 approved these changes
Nickel, c'est tout bon pour moi

2022-12-12 17:05 UTC, merged